# 应用服务web访问端口
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/traffic_db?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
upload:
  path: F:/idealproject/SmartTransport/SmartTransportBackEnd/uploads
  url:
    prefix: /emergency_photos

